excluded:
- Carthage
- Pods
- SwiftGraphics_UnitTests
- Externals
- Playgrounds

disabled_rules:
- file_length
- force_cast
- force_try
- function_body_length
- line_length
- statement_position
- todo
- type_body_length
- valid_docs
- variable_name_min_length

enabled_rules:
- empty_count
#- missing_docs

#line_length: 256
# they can set both implicitly with an array
#type_body_length:
#  warning: 300
#  error: 400
#file_length:
#  warning: 500
#  error: 1200
