disabled_rules:
- file_length
- force_cast
- force_try
- function_body_length
- line_length
- statement_position
- todo
- type_body_length
- valid_docs
- variable_name
- variable_name_min_length
excluded:
- Carthage
- Pods
- UnitTests
