language: objective-c
osx_image: xcode7.2
script:
- xctool -project SwiftGraphics.xcodeproj -scheme SwiftGraphics_iOS -sdk iphonesimulator build test
- xctool -project SwiftGraphics.xcodeproj -scheme SwiftGraphics_OSX build test
- xctool -project SwiftGraphics.xcodeproj -scheme SwiftGraphics_OSX_Playground build test
